variables:
  SOLUTION: "Alma.Infra.sln"
  CONFIGURATION: "Release"

  MSBUILD: "15.0"
  VISUALSTUDIO: "15.0"
  VERBOSITY: "minimal"

  PUBLISHDBPROJ: ""
  PUBLISHPROJ: ""
  DEVELOPMENTPROFILE: ""
  STAGINGPROFILE: ""
  STAGINGPASSWORD: ""
  PRODUCTIONPROFILE: ""

  NUGETREPOSITORY: "https://dev.almasistemas.com.br/nuget/alma"

  AUTHORS: "Marcos Junior and Alex Duraes"
  COMPANY: "Alma Sistemas"
  PRODUCT: "Alma Infrastructure"
  COPYRIGHT: "Copyright (c) Alma Sistemas"
  URL: "dev.almasistemas.com.br"
  URLICON: "dev.almasistemas.com.br/gitlab/uploads/appearance/header_logo/1/ghost-icon.png"

cache:
    key: "$CI_PROJECT_PATH_$CI_BUILD_REF_NAME"
    paths:
        - "packages"
        - "*/obj"
        - "*/*/obj"
        - "*/*/*/obj"
        - "*/*/*/*/obj"

before_script:
  - export PACKVERSION=3.`date -u +%y.%m%d.%H%M`;echo $PACKVERSION
  - msbuild "$SOLUTION" -t:restore -tv:$MSBUILD -verbosity:$VERBOSITY -p:Configuration=$CONFIGURATION -p:VisualStudioVersion=$VISUALSTUDIO -p:GeneratePackageOnBuild=false

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  variables:
    BUILDACTION: "Clean,Build"
  script:
    - msbuild "$SOLUTION" -t:$BUILDACTION -tv:$MSBUILD -verbosity:$VERBOSITY -p:Configuration=$CONFIGURATION -p:VisualStudioVersion=$VISUALSTUDIO -p:GeneratePackageOnBuild=false
  tags:
    - windows

Test:
  stage: test
  variables:
    BUILDACTION: "Clean,Build"
  script:
    - msbuild "$SOLUTION" -t:$BUILDACTION -tv:$MSBUILD -verbosity:$VERBOSITY -p:Configuration=$CONFIGURATION -p:VisualStudioVersion=$VISUALSTUDIO -p:GeneratePackageOnBuild=false
    - gitlab-mstest.sh
  tags:
    - windows
  artifacts:
    when: always
    paths: 
      - TestResults/*.trx
      - TestResults/*.html

ProGet:
  stage: deploy
  environment: Producao
  variables:
    BUILDACTION: "Clean,Restore,Build"
    VERSIONINFO: ""
  script:
    - msbuild "$SOLUTION" -t:$BUILDACTION -tv:$MSBUILD -verbosity:$VERBOSITY -p:Configuration=$CONFIGURATION -p:VisualStudioVersion=$VISUALSTUDIO -p:Version=$PACKVERSION$VERSIONINFO -p:AssemblyVersion=$PACKVERSION -property:Authors="$AUTHORS" -property:Company="$COMPANY" -property:Product="$PRODUCT" -property:Copyright="$COPYRIGHT" -property:URL="$URL" -property:URLICON="$URLICON" -property:GeneratePackageOnBuild=true
    - shopt -s globstar
    - for i in **/bin/$CONFIGURATION/**/*.nupkg; do # Whitespace-safe and recursive
    -     nuget push -ApiKey $NUGETAPIKEY -Source $NUGETREPOSITORY "$i"
    - done
  only:
    - master
  tags:
    - windows

ProGet:
  stage: deploy
  environment: Beta
  variables:
    BUILDACTION: "Clean,Restore,Build"
    VERSIONINFO: "-beta"
  script:
    - msbuild "$SOLUTION" -t:$BUILDACTION -tv:$MSBUILD -verbosity:$VERBOSITY -p:Configuration=$CONFIGURATION -p:VisualStudioVersion=$VISUALSTUDIO -p:Version=$PACKVERSION$VERSIONINFO -p:AssemblyVersion=$PACKVERSION -property:Authors="$AUTHORS" -property:Company="$COMPANY" -property:Product="$PRODUCT" -property:Copyright="$COPYRIGHT" -property:URL=$URL -property:URLICON="$URLICON" -property:GeneratePackageOnBuild=true
    - shopt -s globstar
    - for i in **/bin/$CONFIGURATION/**/*.nupkg; do # Whitespace-safe and recursive
    -     nuget push -ApiKey $NUGETAPIKEY -Source $NUGETREPOSITORY "$i"
    - done
  only:
    - beta
  tags:
    - windows
