variables:
  SOLUTION: "alma-Infrastructure.sln"
  CONFIGURATION: "Release"

  MSBUILD: "15.0"
  VISUALSTUDIO: "15.0"
  VERBOSITY: "minimal"

  PUBLISHDBPROJ: ""
  PUBLISHPROJ: ""
  DEVELOPMENTPROFILE: ""
  STAGINGPROFILE: ""
  STAGINGPASSWORD: ""
  PRODUCTIONPROFILE: ""

  NUGETREPOSITORY: "https://dev.almasistemas.com.br/nuget/alma"

  AUTHORS: "Marcos Junior and Alex Duraes"
  COMPANY: "Marcos Junior and Alex Duraes"
  PRODUCT: "Common Infrastructure"
  COPYRIGHT: "Copyright (c) Marcos Junior and Alex Duraes"
  ICON_URL: "https://avatars2.githubusercontent.com/u/46223903?s=200&v=4"
  PROJECT_URL: "https://github.com/alma-sys"
  REPOSITORY_URL: "https://github.com/alma-sys/alma-infra"

cache:
    key: "${CI_PROJECT_PATH}_${CI_BUILD_REF_NAME}_${CI_PIPELINE_ID}"
    paths:
        - "packages"
        - "*/obj"
        - "*/*/obj"
        - "*/*/*/obj"
        - "*/*/*/*/obj"
        - "*/bin"
        - "*/*/bin"
        - "*/*/*/bin"
        - "*/*/*/*/bin"

before_script:
  - export PACKVERSION=3.`date -u +%y.%m%d.%H%M`;
  - if [[ $CI_COMMIT_REF_SLUG == *"beta"* ]]; then 
  -     export VERSIONINFO="-beta"; 
  - fi
  - echo "Version=$PACKVERSION$VERSIONINFO";

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  variables:
    BUILDACTION: "Clean,Build"
  script:
    - nuget restore
    - msbuild "$SOLUTION" -t:$BUILDACTION -tv:$MSBUILD -verbosity:$VERBOSITY -p:Configuration=$CONFIGURATION -p:VisualStudioVersion=$VISUALSTUDIO -p:Version=$PACKVERSION$VERSIONINFO -p:AssemblyVersion=$PACKVERSION -property:Authors="$AUTHORS" -property:Company="$COMPANY" -property:Product="$PRODUCT" -property:Copyright="$COPYRIGHT" -property:PROJECT_URL="$PROJECT_URL" -property:ICON_URL="$ICON_URL" -property:GeneratePackageOnBuild=true
  tags:
    - windows
  only:
    - branches
    - merge_requests

Test:
  stage: test
  variables:
    GIT_STRATEGY: none
    BUILDACTION: "Clean,Build"
  script:
    - gitlab-mstest.sh
  tags:
    - windows
  only:
    - branches
    - merge_requests
  artifacts:
    when: always
    paths: 
      - TestResults/*.trx
      - TestResults/*.html
# Disabled to set push using circleci. 

#Deploy:
#  stage: deploy
#  environment: PRODUCTION
#  variables:
#    GIT_STRATEGY: none
#  script:
#    - pwd
#    - shopt -s globstar && for i in **/bin/$CONFIGURATION/**/*.nupkg; do # Whitespace-safe and recursive
#    -     nuget push -ApiKey $NUGETAPIKEY -Source $NUGETREPOSITORY "$i"
#    - done
#  only:
#    - master
#  tags:
#    - windows
#
#Deploy:
#  stage: deploy
#  environment: BETA
#  variables:
#    GIT_STRATEGY: none
#  script:
#    - pwd
#    - shopt -s globstar && for i in **/bin/$CONFIGURATION/**/*.nupkg; do # Whitespace-safe and recursive
#    -     nuget push -ApiKey $NUGETAPIKEY -Source $NUGETREPOSITORY "$i"
#    - done
#  only:
#    - /^release\/.*beta.*/
#  tags:
#    - windows
#