variables:
  SOLUTION: "alma-Infrastructure.sln"
  CONFIGURATION: "Release"

  MSBUILD: "15.0"
  VISUALSTUDIO: "15.0"
  VERBOSITY: "minimal"

  PUBLISHDBPROJ: ""
  PUBLISHPROJ: ""
  DEVELOPMENTPROFILE: ""
  STAGINGPROFILE: ""
  STAGINGPASSWORD: ""
  PRODUCTIONPROFILE: ""

  NUGETREPOSITORY: "https://dev.almasistemas.com.br/nuget/alma"

  AUTHORS: "Marcos Junior and Alex Duraes"
  COMPANY: "Marcos Junior and Alex Duraes"
  PRODUCT: "Common Infrastructure"
  COPYRIGHT: "Copyright (c) Marcos Junior and Alex Duraes"
  ICON_URL: "https://dev.almasistemas.com.br/gitlab/uploads/appearance/header_logo/1/ghost-icon.png"
  PROJECT_URL: "https://dev.almasistemas.com.br/gitlab/almatec/alma-infra"
  REPOSITORY_URL: "https://dev.almasistemas.com.br/gitlab/almatec/alma-infra"
  LICENSE_URL: "https://dev.almasistemas.com.br/gitlab/almatec/alma-infra/blob/master/LICENSE.md"

cache:
    key: "$CI_PROJECT_PATH_$CI_BUILD_REF_NAME"
    paths:
        - "packages"
        - "*/obj"
        - "*/*/obj"
        - "*/*/*/obj"
        - "*/*/*/*/obj"
        - "*/bin"
        - "*/*/bin"
        - "*/*/*/bin"
        - "*/*/*/*/bin"

before_script:
  - export PACKVERSION=3.`date -u +%y.%m%d.%H%M`;
  - if [[ $CI_COMMIT_REF_SLUG == *"beta"* ]]; then 
  -     export $VERSIONINFO="-beta"; 
  - fi
  - echo "Version=$PACKVERSION$VERSIONINFO";

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  variables:
    BUILDACTION: "Clean,Build"
  script:
    - msbuild "$SOLUTION" -t:$BUILDACTION -tv:$MSBUILD -verbosity:$VERBOSITY -p:Configuration=$CONFIGURATION -p:VisualStudioVersion=$VISUALSTUDIO -p:Version=$PACKVERSION$VERSIONINFO -p:AssemblyVersion=$PACKVERSION -property:Authors="$AUTHORS" -property:Company="$COMPANY" -property:Product="$PRODUCT" -property:Copyright="$COPYRIGHT" -property:PROJECT_URL="$PROJECT_URL" -property:LICENSE_URL="$LICENSE_URL" -property:ICON_URL="$ICON_URL" -property:GeneratePackageOnBuild=true
  tags:
    - windows
  only:
    - branches
    - merge_requests

Test:
  stage: test
  variables:
    GIT_STRATEGY: none
    BUILDACTION: "Clean,Build"
  script:
    - gitlab-mstest.sh
  tags:
    - windows
  only:
    - branches
    - merge_requests
  artifacts:
    when: always
    paths: 
      - TestResults/*.trx
      - TestResults/*.html

Deploy:
  stage: deploy
  environment: PRODUCTION
  variables:
    GIT_STRATEGY: none
    BUILDACTION: "Clean,Restore,Build"
  script:
    - shopt -s globstar
    - for i in **/bin/$CONFIGURATION/**/*.nupkg; do # Whitespace-safe and recursive
    -     nuget push -ApiKey $NUGETAPIKEY -Source $NUGETREPOSITORY "$i"
    - done
  only:
    - master
  tags:
    - windows
